AWSTemplateFormatVersion: '2010-09-09'
Description: 'Weather Dashboard Infrastructure - Lambda, API Gateway, S3, and IAM'

Parameters:
  OpenWeatherApiKey:
    Type: String
    Description: OpenWeatherMap API Key
    NoEcho: true
  
  ProjectName:
    Type: String
    Default: weather-dashboard
    Description: Project name for resource naming

Resources:
  # IAM Role for Lambda Function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: LambdaCloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ProjectName}-function:*'

  # Lambda Function
  WeatherLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-function'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          OPENWEATHER_API_KEY: !Ref OpenWeatherApiKey
          API_RATE_LIMIT: '60'
          LOG_LEVEL: 'INFO'
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - Deploy actual code' })
            };
          };

  # CloudWatch Log Group
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-function'
      RetentionInDays: 7

  # API Gateway REST API
  WeatherApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${ProjectName}-api'
      Description: Weather Dashboard API
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Gateway Resource - /weather
  WeatherResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref WeatherApiGateway
      ParentId: !GetAtt WeatherApiGateway.RootResourceId
      PathPart: weather

  # API Gateway Resource - /forecast
  ForecastResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref WeatherApiGateway
      ParentId: !GetAtt WeatherApiGateway.RootResourceId
      PathPart: forecast

  # API Gateway Method - GET /weather
  WeatherGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref WeatherApiGateway
      ResourceId: !Ref WeatherResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WeatherLambdaFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # API Gateway Method - GET /forecast
  ForecastGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref WeatherApiGateway
      ResourceId: !Ref ForecastResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WeatherLambdaFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # CORS OPTIONS Method for /weather
  WeatherOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref WeatherApiGateway
      ResourceId: !Ref WeatherResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # CORS OPTIONS Method for /forecast
  ForecastOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref WeatherApiGateway
      ResourceId: !Ref ForecastResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - WeatherGetMethod
      - ForecastGetMethod
      - WeatherOptionsMethod
      - ForecastOptionsMethod
    Properties:
      RestApiId: !Ref WeatherApiGateway
      StageName: prod

  # Lambda Permission for API Gateway - Weather
  WeatherLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WeatherLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WeatherApiGateway}/*/*'

Outputs:
  ApiGatewayUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${WeatherApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${ProjectName}-api-url'
  
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt WeatherLambdaFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-lambda-arn'
  
  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref WeatherLambdaFunction
    Export:
      Name: !Sub '${ProjectName}-lambda-name'
