AWSTemplateFormatVersion: '2010-09-09'
Description: 'Weather Dashboard Monitoring and Alarms'

Parameters:
  ProjectName:
    Type: String
    Default: weather-dashboard
    Description: Project name for resource naming
  
  LambdaFunctionName:
    Type: String
    Description: Lambda function name to monitor
  
  ApiGatewayName:
    Type: String
    Description: API Gateway name to monitor
  
  AlarmEmail:
    Type: String
    Description: Email address for alarm notifications

Resources:
  # SNS Topic for Alarms
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-alarms'
      DisplayName: Weather Dashboard Alarms
      Subscription:
        - Endpoint: !Ref AlarmEmail
          Protocol: email

  # Lambda Error Rate Alarm
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-lambda-errors'
      AlarmDescription: Alert when Lambda error rate exceeds 5%
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      AlarmActions:
        - !Ref AlarmTopic
      TreatMissingData: notBreaching

  # Lambda Duration Alarm
  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-lambda-duration'
      AlarmDescription: Alert when Lambda duration exceeds 8 seconds
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 8000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      AlarmActions:
        - !Ref AlarmTopic
      TreatMissingData: notBreaching

  # API Gateway 5xx Error Alarm
  ApiGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-api-5xx-errors'
      AlarmDescription: Alert when API Gateway 5xx error rate exceeds 1%
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiGatewayName
      AlarmActions:
        - !Ref AlarmTopic
      TreatMissingData: notBreaching

  # Lambda Invocation Count Dashboard
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ProjectName}-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Invocations", {"stat": "Sum", "label": "Invocations"}],
                  [".", "Errors", {"stat": "Sum", "label": "Errors"}],
                  [".", "Duration", {"stat": "Average", "label": "Avg Duration"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Lambda Metrics",
                "dimensions": {
                  "FunctionName": "${LambdaFunctionName}"
                }
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApiGateway", "Count", {"stat": "Sum", "label": "Requests"}],
                  [".", "4XXError", {"stat": "Sum", "label": "4xx Errors"}],
                  [".", "5XXError", {"stat": "Sum", "label": "5xx Errors"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "API Gateway Metrics",
                "dimensions": {
                  "ApiName": "${ApiGatewayName}"
                }
              }
            }
          ]
        }

Outputs:
  AlarmTopicArn:
    Description: SNS Topic ARN for Alarms
    Value: !Ref AlarmTopic
    Export:
      Name: !Sub '${ProjectName}-alarm-topic'
  
  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub 'https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${ProjectName}-dashboard'
